version: "3.8"

services:
  client:
    depends_on:
      - server
    build: ./client
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:3000

    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  server:
    depends_on:
      - mongo
      
    build: ./server
    ports:
      - 3000:3000

    environment:
      MONGO_URI: mongodb://root:password@mongo:27017/docker-demo?authSource=admin

    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data:

  
